// =============================================================================
// fir_filter.v
// 16-tap Direct-Form FIR filter, fixed-point Q1.15 coefficients/data.
// Structure: shift-register delay line -> 16 parallel multipliers -> adder tree
//            -> registered, rescaled output.
// Pipelined by one clock: data_out is valid one cycle after data_valid_in
// (plus internal pipeline latency shown by data_valid_out).
// =============================================================================
module fir_filter #(
    parameter DATA_WIDTH  = 16,   // input/output sample width (Q1.15)
    parameter COEFF_WIDTH = 16,   // coefficient width (Q1.15)
    parameter NUM_TAPS    = 16,
    parameter ACC_WIDTH   = 36    // accumulator width, must be >= DATA_WIDTH+COEFF_WIDTH+log2(NUM_TAPS)
)(
    input  wire                          clk,
    input  wire                          rst_n,          // active-low synchronous reset
    input  wire                          data_valid_in,
    input  wire signed [DATA_WIDTH-1:0]  data_in,
    output reg                           data_valid_out,
    output reg  signed [DATA_WIDTH-1:0]  data_out
);

    // -------------------------------------------------------------------
    // Coefficients: generated by fir_coeff_gen.m (Q1.15, 16-bit signed)
    // -------------------------------------------------------------------
    `include "fir_coeffs.vh"

    wire signed [COEFF_WIDTH-1:0] coeff [0:NUM_TAPS-1];
    assign coeff[0]  = COEFF_0;
    assign coeff[1]  = COEFF_1;
    assign coeff[2]  = COEFF_2;
    assign coeff[3]  = COEFF_3;
    assign coeff[4]  = COEFF_4;
    assign coeff[5]  = COEFF_5;
    assign coeff[6]  = COEFF_6;
    assign coeff[7]  = COEFF_7;
    assign coeff[8]  = COEFF_8;
    assign coeff[9]  = COEFF_9;
    assign coeff[10] = COEFF_10;
    assign coeff[11] = COEFF_11;
    assign coeff[12] = COEFF_12;
    assign coeff[13] = COEFF_13;
    assign coeff[14] = COEFF_14;
    assign coeff[15] = COEFF_15;

    // -------------------------------------------------------------------
    // Delay line (shift register)
    // -------------------------------------------------------------------
    reg signed [DATA_WIDTH-1:0] shift_reg [0:NUM_TAPS-1];
    integer i;

    always @(posedge clk) begin
        if (!rst_n) begin
            for (i = 0; i < NUM_TAPS; i = i + 1)
                shift_reg[i] <= {DATA_WIDTH{1'b0}};
        end else if (data_valid_in) begin
            shift_reg[0] <= data_in;
            for (i = 1; i < NUM_TAPS; i = i + 1)
                shift_reg[i] <= shift_reg[i-1];
        end
    end

    // -------------------------------------------------------------------
    // MAC: combinational sum-of-products (adder tree synthesizes fine;
    // for higher Fmax this can be pipelined into a tree of registers)
    // -------------------------------------------------------------------
    reg signed [ACC_WIDTH-1:0] acc;
    always @(*) begin
        acc = {ACC_WIDTH{1'b0}};
        for (i = 0; i < NUM_TAPS; i = i + 1)
            acc = acc + (shift_reg[i] * coeff[i]);
    end

    // -------------------------------------------------------------------
    // Output register: product of two Q1.15 numbers is Q2.30.
    // Round (add 0.5 LSB) then shift right by 15 to rescale back to Q1.15,
    // then take the low DATA_WIDTH bits.
    // -------------------------------------------------------------------
    wire signed [ACC_WIDTH-1:0] acc_rounded = acc + (1 <<< 14);   // round to nearest
    wire signed [ACC_WIDTH-1:0] acc_scaled  = acc_rounded >>> 15;

    always @(posedge clk) begin
        if (!rst_n) begin
            data_out       <= {DATA_WIDTH{1'b0}};
            data_valid_out <= 1'b0;
        end else begin
            data_out       <= acc_scaled[DATA_WIDTH-1:0];
            data_valid_out <= data_valid_in;
        end
    end

endmodule
