// =============================================================================
// fir_tb.v
// Testbench for fir_filter.v — feeds a 1 kHz test tone (generated by
// fir_coeff_gen.m into fir_input.mem) through the filter, one sample per
// clock, and writes the filtered output to fir_output.mem plus the
// transcript, for comparison against MATLAB's `filter(b,1,x)` result.
// =============================================================================
`timescale 1ns/1ps

module fir_tb;

    localparam DATA_WIDTH  = 16;
    localparam NUM_SAMPLES = 50;      // must match number of lines in fir_input.mem
    localparam CLK_PERIOD  = 10;      // 100 MHz

    reg                          clk;
    reg                          rst_n;
    reg                          data_valid_in;
    reg  signed [DATA_WIDTH-1:0] data_in;
    wire                         data_valid_out;
    wire signed [DATA_WIDTH-1:0] data_out;

    reg [DATA_WIDTH-1:0] input_mem [0:NUM_SAMPLES-1];
    integer outfile;
    integer i;

    // ---------------------------------------------------------------
    // DUT
    // ---------------------------------------------------------------
    fir_filter #(
        .DATA_WIDTH  (16),
        .COEFF_WIDTH (16),
        .NUM_TAPS    (16),
        .ACC_WIDTH   (36)
    ) dut (
        .clk            (clk),
        .rst_n          (rst_n),
        .data_valid_in  (data_valid_in),
        .data_in        (data_in),
        .data_valid_out (data_valid_out),
        .data_out       (data_out)
    );

    // ---------------------------------------------------------------
    // Clock
    // ---------------------------------------------------------------
    initial clk = 1'b0;
    always #(CLK_PERIOD/2) clk = ~clk;

    // ---------------------------------------------------------------
    // Stimulus
    // ---------------------------------------------------------------
    initial begin
        $readmemh("fir_input.mem", input_mem);
        outfile = $fopen("fir_output.mem", "w");

        rst_n         = 1'b0;
        data_valid_in = 1'b0;
        data_in       = {DATA_WIDTH{1'b0}};

        repeat (3) @(posedge clk);
        rst_n = 1'b1;
        @(posedge clk);

        for (i = 0; i < NUM_SAMPLES; i = i + 1) begin
            @(negedge clk);
            data_in       = input_mem[i];
            data_valid_in = 1'b1;
        end
        @(negedge clk);
        data_valid_in = 1'b0;

        // Let the pipeline flush
        repeat (10) @(posedge clk);

        $fclose(outfile);
        $display("Simulation complete: %0d samples processed.", NUM_SAMPLES);
        $finish;
    end

    // ---------------------------------------------------------------
    // Capture output samples
    // ---------------------------------------------------------------
    always @(posedge clk) begin
        if (data_valid_out) begin
            $fwrite(outfile, "%h\n", data_out);
            $display("t=%0t ns  data_out = %0d", $time, data_out);
        end
    end

endmodule
