// Auto-generated FIR coefficients (Q1.15, 16-bit signed)
// 16-tap Hamming-window low-pass FIR, Fc=4kHz, Fs=48kHz
// Generated by fir_coeff_gen.m (MATLAB) -- values below match that script's output
localparam signed [15:0] COEFF_0 = -16'sd84;
localparam signed [15:0] COEFF_1 = -16'sd53;
localparam signed [15:0] COEFF_2 = 16'sd122;
localparam signed [15:0] COEFF_3 = 16'sd700;
localparam signed [15:0] COEFF_4 = 16'sd1817;
localparam signed [15:0] COEFF_5 = 16'sd3331;
localparam signed [15:0] COEFF_6 = 16'sd4814;
localparam signed [15:0] COEFF_7 = 16'sd5737;
localparam signed [15:0] COEFF_8 = 16'sd5737;
localparam signed [15:0] COEFF_9 = 16'sd4814;
localparam signed [15:0] COEFF_10 = 16'sd3331;
localparam signed [15:0] COEFF_11 = 16'sd1817;
localparam signed [15:0] COEFF_12 = 16'sd700;
localparam signed [15:0] COEFF_13 = 16'sd122;
localparam signed [15:0] COEFF_14 = -16'sd53;
localparam signed [15:0] COEFF_15 = -16'sd84;
